<a href="https://colab.research.google.com/github/charith7287/DA_DS_coding_part-/blob/main/DA_DS_12%7Bmini_project%7D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#Connect to Google Drive

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

#Load the data into DataFrame

In [ ]:
df=pd.read_csv("/content/StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df["parental level of education"]

0       bachelor's degree
1            some college
2         master's degree
3      associate's degree
4            some college
              ...
995       master's degree
996           high school
997           high school
998          some college
999          some college
Name: parental level of education, Length: 1000, dtype: object

#Select all the student records with parents having a Master's Degree

In [ ]:
mast_deg=df[df["parental level of education"]=="master's degree"]
mast_deg

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
14,female,group A,master's degree,standard,none,50,53,58
18,male,group C,master's degree,free/reduced,completed,46,42,46
25,male,group A,master's degree,free/reduced,none,73,74,72
29,female,group D,master's degree,standard,none,62,70,75
32,female,group E,master's degree,free/reduced,none,56,72,65
79,female,group E,master's degree,standard,none,62,68,68
106,female,group D,master's degree,standard,none,87,100,100
128,male,group D,master's degree,standard,none,82,82,74
130,male,group D,master's degree,standard,none,89,84,82
162,male,group B,master's degree,free/reduced,none,49,53,52
164,female,group E,master's degree,standard,none,81,92,91
167,female,group B,master's degree,free/reduced,completed,58,76,78
175,female,group C,master's degree,standard,completed,81,91,87
178,female,group B,master's degree,free/reduced,completed,52,70,62
180,male,group C,master's degree,free/reduced,completed,62,68,75
194,female,group C,master's degree,standard,completed,69,84,85
225,female,group E,master's degree,free/reduced,none,45,56,54
253,male,group D,master's degree,standard,none,80,80,72
259,female,group C,master's degree,free/reduced,completed,65,81,81
316,female,group D,master's degree,standard,completed,77,82,91
377,female,group D,master's degree,free/reduced,completed,85,95,100
382,male,group C,master's degree,free/reduced,none,79,81,71
389,male,group D,master's degree,standard,none,73,70,75
410,female,group D,master's degree,standard,completed,70,71,74
422,female,group D,master's degree,free/reduced,completed,47,58,67
478,female,group D,master's degree,standard,none,55,64,70
500,female,group D,master's degree,standard,none,74,79,82
504,female,group D,master's degree,free/reduced,none,40,59,54
508,male,group C,master's degree,standard,none,79,78,77
514,female,group B,master's degree,free/reduced,completed,77,97,94
523,male,group C,master's degree,free/reduced,none,54,59,50
544,female,group D,master's degree,standard,none,64,63,66
549,male,group C,master's degree,standard,none,79,72,69
557,male,group C,master's degree,free/reduced,none,61,67,66
567,female,group D,master's degree,free/reduced,completed,61,71,78
579,female,group D,master's degree,standard,none,53,61,68
600,female,group D,master's degree,standard,none,54,60,63
604,male,group D,master's degree,free/reduced,completed,84,89,90
607,female,group C,master's degree,free/reduced,none,40,58,54
618,male,group D,master's degree,standard,none,95,81,84
685,female,group E,master's degree,standard,completed,94,99,100
713,male,group D,master's degree,standard,none,81,81,84
735,male,group C,master's degree,standard,none,67,57,59
752,male,group C,master's degree,free/reduced,completed,79,77,75
781,female,group B,master's degree,standard,none,77,90,84
789,female,group C,master's degree,free/reduced,none,52,65,61
812,female,group C,master's degree,standard,completed,54,64,67
845,male,group E,master's degree,standard,none,90,85,84
846,male,group C,master's degree,standard,completed,91,85,85
850,male,group C,master's degree,standard,none,71,67,67
861,female,group E,master's degree,free/reduced,none,81,86,87
892,female,group A,master's degree,free/reduced,none,50,67,73
900,male,group D,master's degree,standard,none,85,84,89
901,female,group C,master's degree,standard,none,73,78,74
940,male,group C,master's degree,free/reduced,completed,72,66,72
941,female,group D,master's degree,standard,none,78,91,96
957,female,group D,master's degree,standard,none,92,100,100
995,female,group E,master's degree,standard,completed,88,99,95

In [ ]:
#number of rows and columns
mast_deg.shape

(59, 8)

In [ ]:
df[df["math score"]>=50]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

#Sort and Group Student Records

In [ ]:
#Sort the Records based on reading score and the score has to be more than 90
df[df["reading score"] >= 90].sort_values(by="reading score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
38,female,group D,associate's degree,free/reduced,completed,75,90,88
325,female,group C,some college,standard,none,82,90,94
359,female,group D,some college,standard,none,80,90,89
376,female,group D,some high school,standard,none,80,90,82
...,...,...,...,...,...,...,...,...
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
962,female,group E,associate's degree,standard,none,100,100,100
957,female,group D,master's degree,standard,none,92,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100

In [ ]:
# 1. Compare average performance in mathematics, reading, and writing
avg_scores = df[['math score', 'reading score', 'writing score']].mean()
print("=== Overall Average Performance ===")
print(avg_scores.round(2))
print("\n")

# 2. Explore performance summaries across selected categories
# Category A: Test Preparation Course
test_prep_summary = df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
print("=== Performance Summary by Test Preparation Course ===")
print(test_prep_summary.round(2))
print("\n")

# Category B: Parental Level of Education
parental_edu_summary = df.groupby('parental level of education')[['math score', 'reading score', 'writing score']].mean()
print("=== Performance Summary by Parental Level of Education ===")
print(parental_edu_summary.round(2))

# 3. Export analysis results to CSV files
test_prep_summary.to_csv('performance_by_test_prep.csv')
parental_edu_summary.to_csv('performance_by_parental_education.csv')
print("\n[System Message] Results successfully exported to CSV files!")

=== Overall Average Performance ===
math score       66.09
reading score    69.17
writing score    68.05
dtype: float64


=== Performance Summary by Test Preparation Course ===
                         math score  reading score  writing score
test preparation course
completed                     69.70          73.89          74.42
none                          64.08          66.53          64.50


=== Performance Summary by Parental Level of Education ===
                             math score  reading score  writing score
parental level of education
associate's degree                67.88          70.93          69.90
bachelor's degree                 69.39          73.00          73.38
high school                       62.14          64.70          62.45
master's degree                   69.75          75.37          75.68
some college                      67.13          69.46          68.84
some high school                  63.50          66.94          64.89

[System Message] Results successfully exported to CSV files!